// Fill out your copyright notice in the Description page of Project Settings.

#include "ArenaBattle.h"
#include "ABGameInstance.h"
#include "Kismet/KismetMathLibrary.h"
#include "ABPawn.h"


// Sets default values
AABPawn::AABPawn()
{
 	// Set this pawn to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	
	Body = CreateDefaultSubobject<UCapsuleComponent>(TEXT("root"));
	RootComponent = Body;
	
	Mesh = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("Mesh"));
	Mesh->SetupAttachment(Body);
	
	Movement = CreateDefaultSubobject<UFloatingPawnMovement>(TEXT("movement"));
	Movement->MaxSpeed = 1200.0f;

	SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	SpringArm->SetupAttachment(Body);

	Camera = CreateDefaultSubobject<UCameraComponent>(TEXT("Camera"));
	Camera->SetupAttachment(SpringArm);
	//Camera->SetRelativeLocationAndRotation(FVector(0.0f, -300.0f, 350.0f), FRotator(-30.0f, 90.0f, 0.0f));

	Body->SetCapsuleHalfHeight(88.0f);
	Body->SetCapsuleRadius(36.0f);
	Mesh->SetRelativeLocationAndRotation(FVector(0.0f, 0.0f, -88.0f), FRotator(0.0f, -90.0f, 0.0f));

	SpringArm->TargetArmLength = 800.0f;
	SpringArm->SetRelativeRotation(FRotator(-45.f, 0.f, 0.f));
	SpringArm->bInheritPitch = false;
	SpringArm->bInheritYaw = false;

	//변수가 중복되지 않게 하기 위해(계속 변수를 공유한다) static을 사용한다.
	static ConstructorHelpers::FObjectFinder<USkeletalMesh>
		SK_Mesh(TEXT("SkeletalMesh'/Game/InfinityBladeWarriors/Character/CompleteCharacters/SK_CharM_FrostGiant.SK_CharM_FrostGiant'"));
	Mesh->SetSkeletalMesh(SK_Mesh.Object);
	//AutoPossessPlayer = EAutoReceiveInput::Player0;

	MaxHP = 100.0f;

	CurrentState = EPlayerState::PEACE;
}

// Called when the game starts or when spawned
void AABPawn::BeginPlay()
{
	Super::BeginPlay();
	CurrentHP = MaxHP;

	int32 NewIndex = FMath::RandRange(0, CharacterAssets.Num() - 1);
	UABGameInstance* ABGameInstance = Cast<UABGameInstance>(GetGameInstance());
	if (ABGameInstance)
	{
		TAssetPtr<USkeletalMesh> NewCharacter = Cast<USkeletalMesh>(ABGameInstance->AssetLoader.SynchronousLoad(CharacterAssets[NewIndex]));
		if (NewCharacter)
		{
			Mesh->SetSkeletalMesh(NewCharacter.Get());
		}
	}
}

// Called every frame
void AABPawn::Tick( float DeltaTime )
{
	Super::Tick( DeltaTime );
	FVector InputVector = FVector(CurrentUpDownVal, CurrentLeftRightVal, 0.0F);
	
	switch (CurrentState)
	{
	case EPlayerState::PEACE:
	{
		if (InputVector.SizeSquared() > 0.0F)
		{
			FRotator TargetRotation = UKismetMathLibrary::MakeRotFromX(InputVector);
			SetActorRotation(TargetRotation);
			AddMovementInput(GetActorForwardVector());
		}
		break;
	}
	case EPlayerState::BATTLE:
		break;
	}
	
}

// Called to bind functionality to input
void AABPawn::SetupPlayerInputComponent(class UInputComponent* InputComponent)
{
	Super::SetupPlayerInputComponent(InputComponent);

	InputComponent->BindAxis("LeftRight", this, &AABPawn::LeftRightInput);
	InputComponent->BindAxis("UpDown", this, &AABPawn::UpDownInput);
	InputComponent->BindAction("NormalAttack", EInputEvent::IE_Pressed, this, &AABPawn::OnPressNormalAttack);
	//InputComponent->BindAction("NormalAttack", EInputEvent::IE_Released, this, &AABPawn::OnPressNormalAttack);
}

void AABPawn::UpDownInput(float NewInputVal)
{
	CurrentUpDownVal = NewInputVal;
}

void AABPawn::LeftRightInput(float NewInputVal)
{
	CurrentLeftRightVal = NewInputVal;
}

void AABPawn::OnPressNormalAttack()
{
	AB_LOG_CALLONLY(Warning);
	CurrentState = EPlayerState::BATTLE;
}

void AABPawn::OnReleaseNormalAttack()
{
}

